<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="ur5e_robotiq_85_gripper">

    <xacro:include filename="$(find rvl_robot_description)/xacro/macros/ur5e_macro.xacro" />
    <xacro:include filename="$(find rvl_robot_description)/xacro/macros/robotiq_arg2f_85_macro.xacro" />
    <xacro:include filename="$(find rvl_robot_description)/xacro/macros/l515.xacro"/>
    <xacro:include filename="$(find rvl_robot_description)/xacro/macros/mounting_plate.xacro"/>


    <xacro:property name="coupling_offset" value="0.0053" />
    <xacro:property name="gripper_height" value="0.1628" />
    <xacro:property name="tool_rotation" value="${pi/2}" />

    <xacro:property name="camera_placement_offset" value="0.12439" />
    <xacro:property name="camera_origin_offset" value="0.0061"/>

    <!-- y offset = camera_width / 2 - plate_offset -->
    <!-- z offset = camera_thickness + mounting_plate_thickness -->
    <xacro:property name="camera_placement_origin" value="0.0 ${0.061/2 - 0.1175} ${0.013 + 0.0053}"/>

    <xacro:macro name="ur5e_with_gripper" params="prefix name:=camera use_nominal_extrinsics:=false add_plug:=true use_mesh:=true">
        <!-- Universal Robot UR 5e Arm -->
        <xacro:ur5e_robot prefix="${prefix}"/>

        <!-- Robotiq 2F-85 2-Finger Gripper -->
        <xacro:robotiq_arg2f_85 prefix="${prefix}" />

        <!-- Onboard Intel RealSense L515 -->
        <xacro:sensor_l515 name="L515" parent="${prefix}tool0" use_nominal_extrinsics="${use_nominal_extrinsics}" add_plug="${add_plug}" use_mesh="${use_mesh}">
            <origin xyz="${camera_placement_origin}" rpy="${pi/2} ${-pi/2} 0.0"/>
        </xacro:sensor_l515>

        <!-- attach mounting plate to tool0 -->
        <xacro:mounting_plate prefix="${prefix}" name="plate"/>
        <joint name="tool0-mounting_plate" type="fixed">
            <parent link= "${prefix}tool0" />
            <child link = "${prefix}plate" />
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 ${pi}" />
        </joint>

        <!-- attach gripper to tool0 -->
        <joint name="tool0-gripper_base" type="fixed">
            <parent link= "${prefix}tool0" />
            <child link = "${prefix}robotiq_arg2f_base_link" />
            <origin xyz="0.0 0.0 ${coupling_offset}" rpy="0.0 0.0 ${tool_rotation}" />
        </joint>

        <!-- Add an additional link to plan with. Oriented like the UR ee_link frame. -->
        <link name="${prefix}gripper_center_tip" />
        <joint name="${prefix}gripper_center_tip_joint" type="fixed">
            <parent link="${prefix}robotiq_arg2f_base_link"/>
            <child link="${prefix}gripper_center_tip"/>
            <origin xyz="0.0 0.0 ${coupling_offset + gripper_height}" rpy="0.0 0.0 0.0"/>
        </joint>

    </xacro:macro>

    <!-- creating the robot -->
    <xacro:ur5e_with_gripper prefix="" />

</robot>